### ISSUE TITLE
KubeCon + CloudNativeCon 2022 - Spain

### ISSUE THREAD

**Issue by isabelizimm** [AICoE/content-pipeline#15] opened 2021-09-28 21:43 UTC
**Conference Name**
KubeCon + CloudNativeCon

**Conference Date**
May 17-20, 2022

**Conference Location**
Valencia, Spain 

**CFP Opens**
Coming soon (normally open Oct-Jan)

**CFP Closes**
Coming soon (normally open Oct-Jan)

**Submission Link**
https://events.linuxfoundation.org/kubecon-cloudnativecon-europe/

**Comment by durandom** [comment] 2021-11-10 14:05
duplicate of https://github.com/AICoE/content-pipeline/issues/42

**Closed by durandom** 2021-11-10 14:05 UTC
Labels: conference
